### ISSUE TITLE
Stuck in carrying mode

### ISSUE THREAD

**Issue by tal2410** [GabrielOlvH/Carrier#31]
Using Carrier 1.8.1 in Valhelsia Fabric 1.0.9.

This occurred after accidentally picking up the quarry from AdditionalEnchantedMiner. I couldn't put it down, and everytime I right-clicked the ground it would place a new quarry, but leave me carrying it.

It looks like the block had some bad nbt data? 

[23:26:38] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Invalid target nbt. {area:{direction:"north",maxX:-214,maxY:75,maxZ:191,minX:-224,minY:71,minZ:181},index:315,maxY:75,minY:71}
	at com.yogpc.qp.machines.quarry.Target.fromNbt(Target.java:39) ~[AdditionalEnchantedMiner-1.17-fabric-17.0.390.jar:?]
	at com.yogpc.qp.machines.quarry.TileQuarry.method_11014(TileQuarry.java:98) ~[AdditionalEnchantedMiner-1.17-fabric-17.0.390.jar:?]
	at me.steven.carrier.impl.CarriableGeneric.tryPlace(CarriableGeneric.java:67) ~[carrier-1.8.1.jar:?]
	at me.steven.carrier.HolderInteractCallback.interact(HolderInteractCallback.java:43) ~[carrier-1.8.1.jar:?]
	at me.steven.carrier.HolderInteractCallback.interact(HolderInteractCallback.java:74) ~[carrier-1.8.1.jar:?]
	at net.minecraft.class_4970$class_4971.handler$zfc000$carrier_interactBlock(class_4970.java:1117) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:938) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:327) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1050) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by AlisterGontineac** [comment]
Yeah, happened to me with a chicken, and I just kept placing chicken backpacks from Traveler's Backpack. God awful noise, and inability to do anything, even after dying

**Comment by EthRitt** [comment]
me too. with the chicken backpack.... kinda sucks because I can't play this world anymore because of it....

**Comment by GabrielOlvH** [comment]
This has been fixed as of version 1.8.2 available on CursEforge. You can type /carrierdelete to delete what you're currently carrying

**Comment by AlisterGontineac** [comment]
Awesome, thank you!
